### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by su314ka** [LordEvron/BTC_bruteforcer#1]
Hi,

I receive the below error. 
E:\BTC_bruteforcer-master>main.py
$$$$$$$$$$$$-------Fetching the top rich BTC addresses online-----$$$$$$$$$$$$$
Traceback (most recent call last):
  File "E:\Downloads\BTC_bruteforcer-master\main.py", line 80, in <module>
    run_main()
  File "E:\Downloads\BTC_bruteforcer-master\main.py", line 48, in run_main
    generate()
  File "E:\Downloads\BTC_bruteforcer-master\main.py", line 42, in generate
    f.write("%s\n" % item)
TypeError: a bytes-like object is required, not 'str'

There are some dependencies that I have to install? how can i solve the error? Thanks!

**Comment by LordEvron** [comment]
are you using python 2? the code is a little old, so i did not port it to python 3. 
So you must use  python 2.7.

**Comment by su314ka** [comment]
I use 3.7. I will try it also with 2.7. Thanks for your answer.

**Comment by LordEvron** [comment]
Let me know if it works.. I just tested on my pc and it still work fine..

**Comment by LordEvron** [comment]
Ok.. Since no answer from you, i assume that the problem has been solved and i will close the issue.
